# Generated by scripts/gen_gradients.py from data/gradients.json. Do not edit.
# Run the script after changing the source file; make check fails on a stale copy.
"""Built-in gradients, for the on-display settings UI runner.

The runner drives the Gradient row by the name the display shows, and the
firmware table it has to agree with (BgAnimThemes.cpp) compiles only outside
GAGGIMATE_SIM, so there is no route the runner could read it from instead.
"""

# The category order the pickers group by.
GRADIENT_CATEGORIES = [
    'Coffee',
    'Fire and Heat',
    'Water and Ice',
    'Nature',
    'Night Sky',
    'Neon',
    'Pastel',
    'Metal and Stone',
]

# A gradient's index here is its stored id, so this list is append only.
GRADIENT_NAMES = [
    'Espresso',
    'Ocean',
    'Violet Dusk',
    'Forest',
    'Sunset',
    'Fire',
    'Ice',
    'Mono',
    'Rose',
    'Gold',
    'Aurora',
    'Cyber',
    'Ember Coal',
    'Deep Space',
    'Teal Reef',
    'Sakura',
    'Lime',
    'Arctic Night',
]

# The category of each gradient, in the same order as GRADIENT_NAMES.
GRADIENT_CATEGORY_OF = [
    'Coffee',
    'Water and Ice',
    'Night Sky',
    'Nature',
    'Fire and Heat',
    'Fire and Heat',
    'Water and Ice',
    'Metal and Stone',
    'Pastel',
    'Metal and Stone',
    'Night Sky',
    'Neon',
    'Fire and Heat',
    'Night Sky',
    'Water and Ice',
    'Pastel',
    'Nature',
    'Water and Ice',
]
