// Generated by scripts/gen_gradients.py from data/gradients.json. Do not edit.
// Run the script after changing the source file; make check fails on a stale copy.

// The category order the pickers group by.
export const BG_THEME_CATEGORIES = [
  'Coffee',
  'Fire and Heat',
  'Water and Ice',
  'Nature',
  'Night Sky',
  'Neon',
  'Pastel',
  'Metal and Stone',
];

// A gradient's index here is its stored id, so this list is append only.
export const BG_THEMES = [
  {
    name: 'Espresso',
    category: 'Coffee',
    stops: ['#080402', '#2a1206', '#6b3413', '#b8703a', '#e8b268', '#f8e6c8'],
  },
  {
    name: 'Ocean',
    category: 'Water and Ice',
    stops: ['#02060c', '#06284a', '#0a5276', '#2596be', '#66d3e8', '#d8f6ff'],
  },
  {
    name: 'Violet Dusk',
    category: 'Night Sky',
    stops: ['#0a0512', '#2a1050', '#5c2a94', '#9a5ad4', '#d09af0', '#f4e2ff'],
  },
  {
    name: 'Forest',
    category: 'Nature',
    stops: ['#020803', '#0c2c12', '#1e5c28', '#46963c', '#8cd464', '#e6ffc8'],
  },
  {
    name: 'Sunset',
    category: 'Fire and Heat',
    stops: ['#0c0410', '#4a1030', '#952038', '#d4542c', '#f89c3c', '#ffe8a0'],
  },
  {
    name: 'Fire',
    category: 'Fire and Heat',
    stops: ['#0a0200', '#401004', '#8c2808', '#d85c10', '#f8a428', '#ffe8b0'],
  },
  {
    name: 'Ice',
    category: 'Water and Ice',
    stops: ['#020408', '#10203c', '#2c4a74', '#5486b4', '#9cc8e4', '#eafaff'],
  },
  {
    name: 'Mono',
    category: 'Metal and Stone',
    stops: ['#000000', '#202020', '#484848', '#808080', '#c0c0c0', '#ffffff'],
  },
  {
    name: 'Rose',
    category: 'Pastel',
    stops: ['#0e0407', '#3c1020', '#7a2440', '#c04868', '#ee8ca4', '#ffdce6'],
  },
  {
    name: 'Gold',
    category: 'Metal and Stone',
    stops: ['#060402', '#2e2008', '#6e5014', '#b48c24', '#e8c453', '#fff0b8'],
  },
  {
    name: 'Aurora',
    category: 'Night Sky',
    stops: ['#010806', '#063020', '#0c6444', '#14a878', '#48e0b0', '#c8ffec'],
  },
  {
    name: 'Cyber',
    category: 'Neon',
    stops: ['#050008', '#240448', '#501090', '#9018d8', '#e030f8', '#ff9cf0'],
  },
  {
    name: 'Ember Coal',
    category: 'Fire and Heat',
    stops: ['#0a0604', '#2b0a06', '#6b1a08', '#b8420f', '#e2751f', '#f4a94a'],
  },
  {
    name: 'Deep Space',
    category: 'Night Sky',
    stops: ['#05050f', '#150a28', '#341840', '#6b2f5e', '#b3477d', '#e6b3d6'],
  },
  {
    name: 'Teal Reef',
    category: 'Water and Ice',
    stops: ['#050a0f', '#0a1c28', '#123a44', '#1f6b6e', '#3fb3a8', '#bdeee0'],
  },
  {
    name: 'Sakura',
    category: 'Pastel',
    stops: ['#0c060a', '#341828', '#6e3050', '#b45c80', '#e896b0', '#ffe0ec'],
  },
  {
    name: 'Lime',
    category: 'Nature',
    stops: ['#040802', '#16300a', '#326016', '#5ea024', '#9ee44c', '#eaffc0'],
  },
  {
    name: 'Arctic Night',
    category: 'Water and Ice',
    stops: ['#020206', '#0a1424', '#1a3048', '#34587c', '#6c94bc', '#c4e4f8'],
  },
];
