#!/usr/bin/env python3
"""
ESP32 Core Dump Analyzer for PlatformIO Projects

This script analyzes ESP32 core dumps generated by PlatformIO projects.
It extracts the ELF core dump from ESP32's proprietary format and uses
GDB to provide detailed crash analysis.

Usage:
    python3 scripts/analyze_coredump.py <coredump_file> [environment_or_elf_file] [elf_file]
    
Examples:
    python3 scripts/analyze_coredump.py /path/to/support.bin
    python3 scripts/analyze_coredump.py /path/to/support.bin display
    python3 scripts/analyze_coredump.py /path/to/support.bin controller
    python3 scripts/analyze_coredump.py /path/to/support.bin display-headless
    python3 scripts/analyze_coredump.py /path/to/support.bin /path/to/firmware.elf
    python3 scripts/analyze_coredump.py /path/to/support.bin display /path/to/firmware.elf

Environments:
    display           - Main display controller (default)
    controller        - Gaggia controller
    display-headless  - Headless display mode

Author: Generated for Gaggimate project
"""

import os
import sys
import subprocess
import tempfile
import shutil
import json
import base64
import re
from pathlib import Path

# scripts/auto_firmware_version.py writes `#define BUILD_GIT_VERSION "<git
# describe output>"` at build time (e.g. "v1.9.8-sleep9-523-g506f6630-dirty"),
# and WebUIPlugin.cpp reports that same string back as the support bundle's
# `versions.displayVersion` (WebUIPlugin.cpp:2030, "SystemTab's support bundle
# ... serializes this whole document as `versions`"). The "-g<hash>" segment
# is git-describe's own signature and is what tells this apart from an
# ordinary version-looking string elsewhere in the binary.
GIT_VERSION_RE = re.compile(rb"v\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)*-g[0-9a-f]{6,}(?:-dirty)?")


def extract_ascii_runs(data, min_len=8):
    """Printable-ASCII substrings of at least min_len bytes: what the
    `strings` utility finds, done in pure Python so this script carries no
    dependency on it beyond GDB itself."""
    runs = []
    start = None
    for i, b in enumerate(data):
        if 0x20 <= b < 0x7F:
            if start is None:
                start = i
        else:
            if start is not None and i - start >= min_len:
                runs.append(data[start:i])
            start = None
    if start is not None and len(data) - start >= min_len:
        runs.append(data[start:])
    return runs


def elf_embedded_git_versions(elf_path):
    """The distinct BUILD_GIT_VERSION-shaped strings embedded in an ELF's
    read-only data. Normally exactly one (the identical literal is used in
    several translation units); more than one is reported as ambiguous rather
    than picking one, because guessing which is the real one would defeat the
    point of the check."""
    with open(elf_path, "rb") as f:
        data = f.read()
    versions = set()
    for run in extract_ascii_runs(data):
        for m in GIT_VERSION_RE.finditer(run):
            versions.add(m.group().decode("ascii"))
    return versions


def check_elf_matches_dump(firmware_elf, support_data, force):
    """Refuse to symbolise a core dump against the wrong firmware.elf.
    GDB's backtrace, `info locals` and disassembly are only meaningful when
    the ELF it reads debug info from is the exact binary that crashed (tools
    F16: this script never used to check that at all). Compares the crashed
    device's own reported build (the support bundle's `versions.
    displayVersion`, i.e. its BUILD_GIT_VERSION) against the same string
    embedded in the candidate firmware.elf. Returns True if the analysis
    should proceed, False if it should stop."""
    crash_version = (support_data.get("versions") or {}).get("displayVersion")
    if not crash_version or crash_version == "unknown":
        print("⚠️  Support bundle carries no build version (old bundle format?): cannot verify the ELF matches the dump.")
        return True
    elf_versions = elf_embedded_git_versions(str(firmware_elf))
    if len(elf_versions) == 0:
        print(f"⚠️  No BUILD_GIT_VERSION-shaped string found in {firmware_elf}: cannot verify it matches the crashed build ({crash_version}).")
        return True
    if len(elf_versions) > 1:
        print(
            f"⚠️  {firmware_elf} carries {len(elf_versions)} different BUILD_GIT_VERSION-shaped strings "
            f"({sorted(elf_versions)}): cannot tell which is its own build, so cannot verify it matches "
            f"the crashed build ({crash_version})."
        )
        return True
    (elf_version,) = elf_versions
    if elf_version == crash_version:
        print(f"✅ ELF build matches the crashed device: {elf_version}")
        return True
    print("❌ REFUSING: this ELF does not match the build that crashed.")
    print(f"   Crashed device reported: {crash_version}")
    print(f"   Candidate ELF is:        {elf_version}")
    print("   Symbolising a dump against the wrong ELF gives a backtrace, locals and")
    print("   disassembly that look plausible and are wrong. Rebuild/flash the matching")
    print("   binary, or pass --force if you understand the mismatch and want it anyway.")
    if force:
        print("   --force given: proceeding anyway.")
        return True
    return False

def find_pio_build_dir(environment="display"):
    """Find the PlatformIO build directory for the given environment."""
    build_dir = Path(".pio/build") / environment
    if not build_dir.exists():
        print(f"❌ Build directory not found: {build_dir}")
        
        # List available environments
        pio_build_root = Path(".pio/build")
        if pio_build_root.exists():
            available_envs = [d.name for d in pio_build_root.iterdir() if d.is_dir()]
            if available_envs:
                print(f"   Available environments: {', '.join(available_envs)}")
            else:
                print("   No built environments found.")
        
        print("   Please build the project first with: pio run")
        print(f"   Or build specific environment: pio run -e {environment}")
        return None
    return build_dir

def find_firmware_elf(build_dir):
    """Find the firmware ELF file in the build directory."""
    elf_file = build_dir / "firmware.elf"
    if not elf_file.exists():
        print(f"❌ Firmware ELF not found: {elf_file}")
        print("   Please build the project first with: pio run")
        return None
    return elf_file

def find_gdb_executable():
    """Find the ESP32-S3 GDB executable."""
    # Try ESP-IDF path first
    gdb_paths = [
        "xtensa-esp32s3-elf-gdb",  # In PATH
        "xtensa-esp32-elf-gdb",    # Generic ESP32 GDB (fallback)
        os.path.expanduser("~/.espressif/tools/xtensa-esp-elf-gdb/*/xtensa-esp-elf-gdb/bin/xtensa-esp32s3-elf-gdb"),
        os.path.expanduser("~/.espressif/tools/xtensa-esp-elf-gdb/*/xtensa-esp-elf-gdb/bin/xtensa-esp32-elf-gdb"),
        # PlatformIO paths
        os.path.expanduser("~/.platformio/packages/toolchain-xtensa-esp32s3/bin/xtensa-esp32s3-elf-gdb"),
        os.path.expanduser("~/.platformio/packages/toolchain-xtensa-esp32/bin/xtensa-esp32-elf-gdb"),
    ]
    
    for gdb_path in gdb_paths:
        if "*" in gdb_path:
            # Handle glob patterns
            import glob
            matches = glob.glob(gdb_path)
            if matches:
                gdb_path = matches[0]
        
        if shutil.which(gdb_path) or os.path.exists(gdb_path):
            print(f"✅ Found GDB: {gdb_path}")
            return gdb_path
    
    print("❌ ESP32 GDB not found!")
    print("   Please install ESP-IDF or ensure PlatformIO toolchain is available")
    print("   Tried looking for:")
    for path in gdb_paths:
        print(f"     - {path}")
    return None

def extract_elf_from_coredump(coredump_file):
    """Extract ELF core dump from ESP32 proprietary format."""
    try:
        with open(coredump_file, 'rb') as f:
            data = f.read()
        
        # Find ELF header (0x7f 'E' 'L' 'F')
        elf_start = data.find(b'\x7fELF')
        if elf_start == -1:
            print("❌ No ELF header found in core dump")
            return None
        
        print(f"✅ ELF header found at offset: {elf_start}")
        
        # Extract ELF data
        elf_data = data[elf_start:]
        
        # Create temporary file
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix='.elf')
        temp_file.write(elf_data)
        temp_file.close()
        
        print(f"✅ Extracted ELF core dump to: {temp_file.name}")
        print(f"   Original size: {len(data)} bytes, ELF size: {len(elf_data)} bytes")
        
        return temp_file.name
        
    except Exception as e:
        print(f"❌ Failed to extract ELF from core dump: {e}")
        return None

def analyze_with_gdb(gdb_path, firmware_elf, coredump_elf):
    """Analyze core dump using GDB."""
    print("\n" + "="*80)
    print("🔍 CORE DUMP ANALYSIS")
    print("="*80)
    
    # GDB commands to run
    gdb_commands = [
        f"core-file {coredump_elf}",
        "bt",  # Backtrace
        "info registers",  # Register dump
        "info threads",  # Thread information
        "thread apply all bt",  # Backtrace for all threads
        "quit"
    ]
    
    # Create GDB command file
    with tempfile.NamedTemporaryFile(mode='w', delete=False, suffix='.gdb') as cmd_file:
        for cmd in gdb_commands:
            cmd_file.write(f"{cmd}\n")
        cmd_file_path = cmd_file.name
    
    try:
        # Run GDB
        result = subprocess.run([
            gdb_path,
            firmware_elf,
            "-x", cmd_file_path,
            "--batch"
        ], capture_output=True, text=True, timeout=60)
        
        print("📋 GDB OUTPUT:")
        print("-" * 40)
        if result.stdout:
            print(result.stdout)
        if result.stderr:
            print("STDERR:", result.stderr)
        
        return result.returncode == 0
        
    except subprocess.TimeoutExpired:
        print("❌ GDB analysis timed out")
        return False
    except Exception as e:
        print(f"❌ GDB analysis failed: {e}")
        return False
    finally:
        # Clean up command file
        try:
            os.unlink(cmd_file_path)
        except:
            pass

def print_crash_summary(coredump_file):
    """Print a summary and recommendations."""
    print("\n" + "="*80)
    print("📊 CRASH ANALYSIS SUMMARY")
    print("="*80)
    print(f"Core dump file: {coredump_file}")
    print("\n💡 NEXT STEPS:")
    print("1. Look at the backtrace (bt) to see the call stack")
    print("2. Check the exact line where the crash occurred")
    print("3. Look for null pointer dereferences or memory access violations")
    print("4. Check register 'pc' (program counter) for the crash address")
    print("5. Use 'info locals' in interactive GDB for variable values")
    print("\n🔧 INTERACTIVE ANALYSIS:")
    print("For deeper analysis, run GDB interactively:")
    print(f"   xtensa-esp32s3-elf-gdb .pio/build/display/firmware.elf")
    print(f"   (gdb) core-file /tmp/extracted_coredump.elf")
    print(f"   (gdb) bt")
    print(f"   (gdb) list")
    print(f"   (gdb) info locals")

def main():
    # --force (skip the build-match refusal below) can appear anywhere in the
    # argument list; strip it out first so the positional parsing below is
    # unaffected by where the caller put it.
    argv = sys.argv[1:]
    force = "--force" in argv
    argv = [a for a in argv if a != "--force"]

    if len(argv) < 1:
        print("Usage: python3 scripts/analyze_coredump.py <coredump_file> [environment_or_elf_file] [elf_file] [--force]")
        print("")
        print("Available environments:")
        print("  display           - Main display controller (default)")
        print("  controller        - Gaggia controller")
        print("  display-headless  - Headless display mode")
        print("")
        print("Examples:")
        print("  python3 scripts/analyze_coredump.py ~/Downloads/coredump.bin")
        print("  python3 scripts/analyze_coredump.py ~/Downloads/coredump.bin display")
        print("  python3 scripts/analyze_coredump.py ~/Downloads/coredump.bin controller")
        print("  python3 scripts/analyze_coredump.py ~/Downloads/coredump.bin /path/to/firmware.elf")
        print("  python3 scripts/analyze_coredump.py ~/Downloads/coredump.bin display /path/to/firmware.elf")
        print("")
        print("--force: symbolise even when the ELF's own BUILD_GIT_VERSION does not match")
        print("         the crashed device's (versions.displayVersion in the support bundle).")
        sys.exit(1)

    support_file = argv[0]
    support_data = {
        'versions': {
            'displayVersion': 'unknown'
        }
    }

    coredump_file = "coredump.bin"
    with open(support_file, 'r') as f:
        support_data = json.load(f)
        coredump = support_data['coredump']
        coredump_binary = base64.b64decode(coredump)
        with open(coredump_file, 'wb') as f2:
            f2.write(coredump_binary)



    # Parse arguments - support both environment and direct ELF file specification
    environment = "display"  # default
    custom_elf_file = None

    if len(argv) >= 2:
        second_arg = argv[1]
        # Check if second argument is an ELF file (has .elf extension or is an absolute/relative path)
        if second_arg.endswith('.elf') or '/' in second_arg or '\\' in second_arg:
            custom_elf_file = second_arg
        else:
            environment = second_arg

    if len(argv) >= 3:
        custom_elf_file = argv[2]

    print("🚀 ESP32 Core Dump Analyzer")
    print("="*50)
    displayVersion = 'unknown'
    if 'displayVersion' in support_data['versions']:
        displayVersion = support_data['versions']['displayVersion']
    print(f"Version: {displayVersion}")
    print(f"Support file: {support_file}")
    print(f"Core dump: {coredump_file}")
    if custom_elf_file:
        print(f"ELF file: {custom_elf_file}")
    else:
        print(f"Environment: {environment}")
    print()
    
    # Validate input file
    if not os.path.exists(coredump_file):
        print(f"❌ Core dump file not found: {coredump_file}")
        sys.exit(1)
    
    # Determine firmware ELF file
    if custom_elf_file:
        if not os.path.exists(custom_elf_file):
            print(f"❌ Custom ELF file not found: {custom_elf_file}")
            sys.exit(1)
        firmware_elf = Path(custom_elf_file)
        print(f"✅ Using custom ELF file: {firmware_elf}")
    else:
        # Find build artifacts using environment
        build_dir = find_pio_build_dir(environment)
        if not build_dir:
            sys.exit(1)
        
        firmware_elf = find_firmware_elf(build_dir)
        if not firmware_elf:
            sys.exit(1)

    # Refuse to symbolise against the wrong build (tools F16) before doing
    # any GDB work: a mismatch here makes every later result look plausible
    # and be wrong.
    if not check_elf_matches_dump(firmware_elf, support_data, force):
        sys.exit(1)

    # Find GDB
    gdb_path = find_gdb_executable()
    if not gdb_path:
        sys.exit(1)
    
    # Extract ELF from core dump
    coredump_elf = extract_elf_from_coredump(coredump_file)
    if not coredump_elf:
        sys.exit(1)
    
    try:
        # Analyze with GDB
        success = analyze_with_gdb(gdb_path, str(firmware_elf), coredump_elf)
        
        # Print summary
        print_crash_summary(coredump_file)
        
        if success:
            print("\n✅ Analysis completed successfully!")
        else:
            print("\n⚠️  Analysis completed with warnings")
            
    finally:
        # Clean up temporary file
        try:
            os.unlink(coredump_elf)
        except:
            pass

if __name__ == "__main__":
    main()
