#!/usr/bin/env python3
"""Turns data/gradients.json into every table that has to know the built-in
animation gradients.

Before this script there were four copies kept in step by hand: the firmware
table in BgAnimThemes.cpp, the web mirror in bgAnimations.js, a names-only
mirror in CatAnimation.cpp written when the simulator could not link the
firmware table (it can since gm-nov3.3, and that copy is gone), and a second
names-only mirror in the settings UI runner, which drives the gradient row by
the name the display shows. Four copies of eighteen gradients is survivable.
Four copies of sixty is not, and the drift is silent: the web picker would
name one gradient while the panel drew another.

Outputs are checked in, so neither the firmware build, the web build, the host
tests nor the settings UI runner need Python at run time:

  src/display/ui/default/bganim/BgAnimThemeTable.h
  web/src/config/bgThemes.js
  tools/settings_ui_tests/gradients_gen.py

Usage:
  python3 scripts/gen_gradients.py            write the outputs
  python3 scripts/gen_gradients.py --check    exit 1 if any output is stale
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'data', 'gradients.json')
HEADER = os.path.join(ROOT, 'src', 'display', 'ui', 'default', 'bganim', 'BgAnimThemeTable.h')
WEB = os.path.join(ROOT, 'web', 'src', 'config', 'bgThemes.js')
RUNNER = os.path.join(ROOT, 'tools', 'settings_ui_tests', 'gradients_gen.py')

# Six, because every animation's palette arithmetic assumes evenly spaced
# stops and the firmware's fast path copies 6 * 3 bytes. A gradient with a
# different count belongs in the user's library, not in this table.
STOPS_PER_GRADIENT = 6

BANNER_C = ('// Generated by scripts/gen_gradients.py from data/gradients.json. Do not edit.\n'
            '// Run the script after changing the source file; make check fails on a stale copy.\n')
BANNER_JS = ('// Generated by scripts/gen_gradients.py from data/gradients.json. Do not edit.\n'
             '// Run the script after changing the source file; make check fails on a stale copy.\n')
BANNER_PY = ('# Generated by scripts/gen_gradients.py from data/gradients.json. Do not edit.\n'
             '# Run the script after changing the source file; make check fails on a stale copy.\n')

HEX = re.compile(r'^#[0-9a-f]{6}$')


def load():
    with open(SOURCE, encoding='utf-8') as f:
        doc = json.load(f)
    cats = doc['categories']
    grads = doc['gradients']
    if not isinstance(cats, list) or not cats:
        die('categories must be a non-empty list')
    seen = set()
    for c in cats:
        if not isinstance(c, str) or not c:
            die('category names must be non-empty strings')
        if c in seen:
            die('duplicate category %r' % c)
        seen.add(c)
    names = set()
    for i, g in enumerate(grads):
        where = 'gradient %d (%r)' % (i, g.get('name'))
        if not g.get('name'):
            die('%s has no name' % where)
        if g['name'] in names:
            die('%s: duplicate name' % where)
        names.add(g['name'])
        if g.get('category') not in seen:
            die('%s: unknown category %r' % (where, g.get('category')))
        stops = g.get('stops')
        if not isinstance(stops, list) or len(stops) != STOPS_PER_GRADIENT:
            die('%s: needs exactly %d stops, has %r'
                % (where, STOPS_PER_GRADIENT, len(stops) if isinstance(stops, list) else stops))
        for s in stops:
            if not isinstance(s, str) or not HEX.match(s):
                die('%s: stop %r is not #rrggbb in lower case' % (where, s))
    return cats, grads


def die(msg):
    sys.stderr.write('gen_gradients: %s\n' % msg)
    raise SystemExit(2)


def c_stops(stops):
    out = []
    for s in stops:
        out.append('{0x%s, 0x%s, 0x%s}' % (s[1:3], s[3:5], s[5:7]))
    return '{' + ', '.join(out) + '}'


def c_str(s):
    return '"%s"' % s.replace('\\', '\\\\').replace('"', '\\"')


def render_header(cats, grads):
    lines = [BANNER_C, '#pragma once\n', '\n', '#include <stdint.h>\n', '\n',
             'namespace bganim_gen {\n', '\n',
             '// One built-in gradient. The index of an entry in THEME_DEFS is its stored\n'
             '// id: bgAnimGradientRef and every slot of bgAnimThemeMap hold it as a decimal\n'
             '// string, so the order of data/gradients.json is append only.\n',
             'struct ThemeDef {\n',
             '    const char *name;\n',
             '    const char *category;\n',
             '    uint8_t stops[%d][3];\n' % STOPS_PER_GRADIENT,
             '};\n', '\n',
             '// clang-format off\n',
             'inline constexpr ThemeDef THEME_DEFS[] = {\n']
    for g in grads:
        lines.append('    {%s, %s, %s},\n'
                     % (c_str(g['name']), c_str(g['category']), c_stops(g['stops'])))
    lines.append('};\n')
    lines.append('\n')
    lines.append('inline constexpr const char *THEME_CATEGORIES[] = {\n')
    for c in cats:
        lines.append('    %s,\n' % c_str(c))
    lines.append('};\n')
    lines.append('// clang-format on\n')
    lines.append('\n')
    lines.append('inline constexpr int THEME_DEF_COUNT = '
                 'static_cast<int>(sizeof(THEME_DEFS) / sizeof(THEME_DEFS[0]));\n')
    lines.append('inline constexpr int THEME_CATEGORY_COUNT = '
                 'static_cast<int>(sizeof(THEME_CATEGORIES) / sizeof(THEME_CATEGORIES[0]));\n')
    lines.append('\n')
    lines.append('} // namespace bganim_gen\n')
    return ''.join(lines)


def js_str(s):
    return "'%s'" % s.replace('\\', '\\\\').replace("'", "\\'")


def render_web(cats, grads):
    out = [BANNER_JS, '\n',
           '// The category order the pickers group by.\n',
           'export const BG_THEME_CATEGORIES = [\n']
    for c in cats:
        out.append('  %s,\n' % js_str(c))
    out.append('];\n')
    out.append('\n')
    out.append("// A gradient's index here is its stored id, so this list is append only.\n")
    out.append('export const BG_THEMES = [\n')
    for g in grads:
        out.append('  {\n')
        out.append('    name: %s,\n' % js_str(g['name']))
        out.append('    category: %s,\n' % js_str(g['category']))
        out.append('    stops: [%s],\n' % ', '.join(js_str(s) for s in g['stops']))
        out.append('  },\n')
    out.append('];\n')
    return ''.join(out)


def py_str(s):
    return "'%s'" % s.replace('\\', '\\\\').replace("'", "\\'")


def render_runner(cats, grads):
    out = [BANNER_PY,
           '"""Built-in gradients, for the on-display settings UI runner.\n',
           '\n',
           'The runner drives the Gradient row by the name the display shows, and the\n',
           'firmware table it has to agree with (BgAnimThemes.cpp) compiles only outside\n',
           'GAGGIMATE_SIM, so there is no route the runner could read it from instead.\n',
           '"""\n',
           '\n',
           '# The category order the pickers group by.\n',
           'GRADIENT_CATEGORIES = [\n']
    for c in cats:
        out.append('    %s,\n' % py_str(c))
    out.append(']\n')
    out.append('\n')
    out.append("# A gradient's index here is its stored id, so this list is append only.\n")
    out.append('GRADIENT_NAMES = [\n')
    for g in grads:
        out.append('    %s,\n' % py_str(g['name']))
    out.append(']\n')
    out.append('\n')
    out.append('# The category of each gradient, in the same order as GRADIENT_NAMES.\n')
    out.append('GRADIENT_CATEGORY_OF = [\n')
    for g in grads:
        out.append('    %s,\n' % py_str(g['category']))
    out.append(']\n')
    return ''.join(out)


def write(path, text, check):
    old = None
    if os.path.exists(path):
        with open(path, encoding='utf-8') as f:
            old = f.read()
    rel = os.path.relpath(path, ROOT)
    if old == text:
        print('gen_gradients: %s up to date' % rel)
        return True
    if check:
        sys.stderr.write('gen_gradients: %s is stale, run scripts/gen_gradients.py\n' % rel)
        return False
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)
    print('gen_gradients: wrote %s' % rel)
    return True


def main():
    check = '--check' in sys.argv[1:]
    cats, grads = load()
    ok = write(HEADER, render_header(cats, grads), check)
    ok = write(WEB, render_web(cats, grads), check) and ok
    ok = write(RUNNER, render_runner(cats, grads), check) and ok
    if not check:
        print('gen_gradients: %d gradients in %d categories' % (len(grads), len(cats)))
        for c in cats:
            print('  %-16s %d' % (c, sum(1 for g in grads if g['category'] == c)))
    return 0 if ok else 1


if __name__ == '__main__':
    sys.exit(main())
