# ruff: noqa: F821 — `env` is injected by PlatformIO/SCons at runtime
import os

Import("env")

env.Append(CXXFLAGS=["-Wno-deprecated-enum-enum-conversion"])

# pioarduino 55.x split WiFi → Network/NetworkClientSecure. Arduino-bundled libs
# declare transitive deps only via `#include`, not `depends=` in
# library.properties, so LDF (even `deep+`) won't wire up sibling include paths
# for every compile unit. Inject a narrow allowlist of Arduino-bundled libs
# we actually use. Keep this list tight — globbing every library pulls in
# paths for framework libs we don't need (protocol stacks, radio helpers, DSP,
# etc.) and can collide or inflate compile time.
#
# CXXFLAGS, not CPPPATH: under dual-framework or hybrid-compile builds IDF C
# sources (e.g. spiffs_api.c, sdmmc_*.c) share the project include path set
# with our C++ code. Arduino's FS.h / SPIFFS's spiffs.h are C++ headers —
# leaking them into C compilation trips `#include <memory>` with "No such
# file or directory". `-I` via CXXFLAGS applies to C++ only.
ARDUINO_LIBS_ALLOWLIST = [
    "Network",
    "NetworkClientSecure",
    "WiFi",
    "HTTPClient",
    "HTTPUpdate",
    "Update",
    "SPI",
    "Wire",
    "FS",
    "SPIFFS",
    "SD_MMC",
    "Preferences",
    "DNSServer",
    "AsyncUDP",
    "ESPmDNS",
    "Ethernet",
    "ArduinoOTA",
    "Hash",
]

# Name shim so esp-nimble-cpp can find PlatformIO's Arduino component -- but only
# when the installed package name forces one.
#
# esp-nimble-cpp 2.5.0 detects a PlatformIO Arduino build by substring-matching
# "___idf_framework-arduinoespressif32" against __COMPONENT_TARGETS, then
# PRIV_REQUIRES the bare name "framework-arduinoespressif32". An IDF component's
# name is the basename of its directory, and pioarduino sometimes unpacks the
# Arduino tree under a hashed directory name
# (framework-arduinoespressif32-src-<md5>) -- typically when a stale package
# already occupies the plain-name slot. Then the substring test passes but the
# bare name is not a registered component and idf_build_process aborts:
#
#   Failed to resolve component 'framework-arduinoespressif32' required by
#   component 'h2zero__esp-nimble-cpp': unknown name.
#
# The fix cannot live in managed_components/ (the component manager regenerates
# it) and cannot come from a version bump (2.5.0 is both the only 2.5.x and the
# newest release), so it is a generated component that forwards to the real one.
#
# It MUST NOT be a tracked file. ESP-IDF resolves a project-local components/
# entry ahead of anything in EXTRA_COMPONENT_DIRS, so whenever the package does
# unpack under the plain name -- which is the normal case on a clean machine, and
# what CI always gets -- a checked-in shim silently REPLACES the real Arduino
# component. Nothing then contributes cores/esp32 to the include set and every
# translation unit fails on `Arduino.h: No such file or directory`, while a
# developer whose package happens to carry the hashed name sees a green build.
# So: generate the shim only when the names actually differ, and remove it when
# they do not.
SHIM_NAME = "framework-arduinoespressif32"
SHIM_CMAKE = """\
# GENERATED by scripts/pioarduino_env.py -- do not edit, do not commit.
# See that script for why this component exists and why it must stay untracked.
idf_build_get_property(_component_targets __COMPONENT_TARGETS)

set(_arduino_components "")
foreach(_target IN LISTS _component_targets)
    if(_target MATCHES "^___idf_(framework-arduinoespressif32-.+)$")
        list(APPEND _arduino_components "${CMAKE_MATCH_1}")
    endif()
endforeach()

if(_arduino_components STREQUAL "")
    message(STATUS "framework-arduinoespressif32 shim: no pioarduino Arduino component found, registering empty")
else()
    message(STATUS "framework-arduinoespressif32 shim: forwarding to ${_arduino_components}")
endif()

# REQUIRES, not PRIV_REQUIRES, so the Arduino include dirs propagate through to
# nimble: with CONFIG_ENABLE_ARDUINO_DEPENDS=y, NimBLEDevice.cpp includes
# esp32-hal-bt.h and calls btStarted().
idf_component_register(REQUIRES ${_arduino_components})
"""
GENERATED_MARKER = "GENERATED by scripts/pioarduino_env.py"


def _sync_arduino_name_shim(project_dir, arduino_pkg_dir):
    shim_dir = os.path.join(project_dir, "components", SHIM_NAME)
    shim_file = os.path.join(shim_dir, "CMakeLists.txt")
    collides = not arduino_pkg_dir or os.path.basename(
        os.path.normpath(arduino_pkg_dir)
    ) == SHIM_NAME

    if collides:
        # The real component already answers to the name nimble asks for. A shim
        # here would shadow it, so make sure ours is gone. Only ever delete a
        # file we generated.
        if os.path.isfile(shim_file):
            with open(shim_file, encoding="utf-8") as handle:
                if GENERATED_MARKER not in handle.read():
                    print(
                        "pioarduino_env: refusing to remove hand-written "
                        + shim_file
                    )
                    return
            os.remove(shim_file)
            try:
                os.rmdir(shim_dir)
            except OSError:
                pass
            print("pioarduino_env: removed Arduino name shim (no longer needed)")
        return

    # Write only on change: rewriting it every build would re-trigger a CMake
    # reconfigure of the whole project.
    if os.path.isfile(shim_file):
        with open(shim_file, encoding="utf-8") as handle:
            if handle.read() == SHIM_CMAKE:
                return
    os.makedirs(shim_dir, exist_ok=True)
    with open(shim_file, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(SHIM_CMAKE)
    print(
        "pioarduino_env: generated Arduino name shim for "
        + os.path.basename(os.path.normpath(arduino_pkg_dir))
    )


platform = env.PioPlatform()
framework_dir = platform.get_package_dir("framework-arduinoespressif32")
if framework_dir:
    libraries_dir = os.path.join(framework_dir, "libraries")
    for name in ARDUINO_LIBS_ALLOWLIST:
        src = os.path.join(libraries_dir, name, "src")
        if os.path.isdir(src):
            env.Append(CXXFLAGS=["-I" + src])

_sync_arduino_name_shim(env.get("PROJECT_DIR", ""), framework_dir)

# IDF BT/NimBLE include paths for esp-nimble-cpp.
# esp-nimble-cpp REQUIRES bt (IDF component), which exposes NimBLE C headers
# (host/ble_gap.h, syscfg/syscfg.h, etc.) transitively. IDF's CMake resolves
# this automatically for the IDF compilation pass, but the Arduino lib
# compilation pass doesn't receive IDF component REQUIRES propagation.
# Inject via CXXFLAGS (same cross-pass mechanism as ARDUINO_LIBS_ALLOWLIST).
#
# Paths extracted from bt/CMakeLists.txt include_dirs declarations —
# IDF uses container dirs (e.g. porting/nimble/include) not leaf dirs,
# so a naive os.walk would add wrong paths and miss header resolution.
_IDF_BT_NIMBLE_PATHS = [
    # Common BT
    "bt/common/osi/include",
    "bt/common/api/include/api",
    "bt/common/btc/profile/esp/blufi/include",
    "bt/common/btc/profile/esp/include",
    "bt/common/hci_log/include",
    "bt/common/ble_log/include",
    "bt/common/tinycrypt/include",
    "bt/common/tinycrypt/port",
    # NimBLE host
    "bt/host/nimble/nimble/nimble/host/include",
    "bt/host/nimble/nimble/nimble/include",
    "bt/host/nimble/nimble/nimble/host/services/ans/include",
    "bt/host/nimble/nimble/nimble/host/services/bas/include",
    "bt/host/nimble/nimble/nimble/host/services/dis/include",
    "bt/host/nimble/nimble/nimble/host/services/gap/include",
    "bt/host/nimble/nimble/nimble/host/services/gatt/include",
    "bt/host/nimble/nimble/nimble/host/services/hr/include",
    "bt/host/nimble/nimble/nimble/host/services/htp/include",
    "bt/host/nimble/nimble/nimble/host/services/ias/include",
    "bt/host/nimble/nimble/nimble/host/services/ipss/include",
    "bt/host/nimble/nimble/nimble/host/services/lls/include",
    "bt/host/nimble/nimble/nimble/host/services/prox/include",
    "bt/host/nimble/nimble/nimble/host/services/cts/include",
    "bt/host/nimble/nimble/nimble/host/services/tps/include",
    "bt/host/nimble/nimble/nimble/host/services/hid/include",
    "bt/host/nimble/nimble/nimble/host/services/sps/include",
    "bt/host/nimble/nimble/nimble/host/services/cte/include",
    "bt/host/nimble/nimble/nimble/host/services/ras/include",
    "bt/host/nimble/nimble/nimble/host/util/include",
    "bt/host/nimble/nimble/nimble/host/store/ram/include",
    "bt/host/nimble/nimble/nimble/host/store/config/include",
    # NimBLE porting layer (syscfg/syscfg.h lives here)
    "bt/host/nimble/nimble/porting/nimble/include",
    "bt/host/nimble/port/include",
    "bt/host/nimble/nimble/nimble/transport/include",
    "bt/porting/include",
    "bt/host/nimble/nimble/porting/npl/freertos/include",
    "bt/host/nimble/esp-hci/include",
]
# Target-specific BT controller API. ESP32-S3 uses the esp32c3-family ABI;
# other targets (S2, C6, H2, P4) would need a different subdir — gate by MCU
# so the wrong header doesn't get pulled in on future ports.
_mcu = env.subst("$BOARD_MCU")
if _mcu in ("esp32s3", "esp32c3", "esp32c2"):
    _IDF_BT_NIMBLE_PATHS.insert(0, "bt/include/esp32c3/include")

idf_dir = platform.get_package_dir("framework-espidf")
if idf_dir:
    components_dir = os.path.join(idf_dir, "components")
    for rel_path in _IDF_BT_NIMBLE_PATHS:
        abs_path = os.path.join(components_dir, rel_path)
        if os.path.isdir(abs_path):
            env.Append(CXXFLAGS=["-I" + abs_path])

# esp-nimble-cpp managed component: C++ wrapper headers (NimBLEDevice.h etc.).
# Managed components live at project root, not inside the PlatformIO package
# tree, so they must be referenced via PROJECT_DIR.
_project_dir = env.get("PROJECT_DIR", "")
if _project_dir:
    _nimble_cpp_src = os.path.join(
        _project_dir, "managed_components", "h2zero__esp-nimble-cpp", "src"
    )
    if os.path.isdir(_nimble_cpp_src):
        env.Append(CXXFLAGS=["-I" + _nimble_cpp_src])
